USE [master]
GO
ALTER DATABASE [DatabaseName] SET QUERY_STORE = ON
GO
ALTER DATABASE [DatabaseName] 
SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), MAX_STORAGE_SIZE_MB = 500)
GO
